### ISSUE TITLE
Install fails on wheezy

### ISSUE THREAD

**Issue by dalyc** [smola/ansible-java-role#10]
I get the following error when trying to install on wheezy (debian 7)

<pre>

GATHERING FACTS *************************************************************** 
ok: [test]

TASK: [smola.java | include_vars Ubuntu.yml] ********************************** 
ok: [test]

TASK: [smola.java | Install python-apt] *************************************** 
ok: [test]

TASK: [smola.java | Install WebUpd8 apt key] ********************************** 
ok: [test]

TASK: [smola.java | Install WebUpd8 Team Java PPA (for Oracle Java)] ********** 
failed: [test] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1437699050.76-118417023704279/apt_repository", line 2854, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1437699050.76-118417023704279/apt_repository", line 449, in main
    if state == 'present' and expanded_repo not in sourceslist.repos_urls:
AttributeError: 'SourcesList' object has no attribute 'repos_urls'
</pre>

**Comment by dalyc** [comment]
Seems to be caused by this https://github.com/ansible/ansible-modules-core/issues/1684
The fix (https://github.com/ansible/ansible-modules-core/pull/1738) still doesn't work for Debian but I was able to workaround by manually editing lib/ansible/modules/core/packaging/os/apt_repository.py
and applying that fix but also copying the fixed repos_urls method from UbuntuSourcesList to SourcesList

I don't understand what's going on well enough to submit a patch but I did comment on the ticket.

**Comment by dalyc** [comment]
This is fixed by https://github.com/ansible/ansible-modules-core/pull/1738
